[package]
name = "screen-sidekick-codex-client"
edition.workspace = true
rust-version.workspace = true
version.workspace = true
publish = false

[dependencies]
async-trait.workspace = true
futures-core.workspace = true
futures-util.workspace = true
screen-sidekick-sidekick-protocol.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
tokio-stream = "0.1"

[dev-dependencies]
tempfile.workspace = true
